### ISSUE TITLE
Black Screen loading mission

### ISSUE THREAD

**Issue by SertinoxVS** [Scarso327/AltisLife-Framework#432]
Hello, i got a black screen after selected my slots i check all database was connected i don't understand if someone has an idea ?

**Comment by Scarso327** [comment]
Hi, without logs of some description, there isn't much I can do to help.

EXTDB3 Logs, Server and Client RPT would provide a great amount of help in resolving this issue for you.

**Comment by Scarso327** [comment]
Someone recently contacted me on Discord with a similar issue and found they hadn't run the migration SQL files for 1.2. I've updated the readme to explain this is a requirement when running dev.

The reason is that the development branch gets updated with new SQL but I don't increment the version number until a live release. Hope this resolves your issue!
