### ISSUE TITLE
Black screen after loading.

### ISSUE THREAD

**Issue by plcaco** [Scarso327/AltisLife-Framework#435]
Hey! 

I've been having issues loading in both the dev build and 1.1.2 release, I can hear myself walk around but stuck on a black screen. Client RPT logs look good and I see myself and other users being written into the DB so that seems fine AFAIK. I saw the comments in #432 and #431 about running the migration SQL on the dev build but I get an error when doing that. Server side RPT logs do have a lot of errors in expression/position. I get up to **"[ULP][v1.1.2] Initialisation Lasted 0.0400009s"** followed by a lot of **Scripting function 'bis_fnc_arsenal' is not allowed to be remotely executed** and with the RPT log then ending in:

`20:21:18 "[ULP][v1.1.2] Registered 76561198016137439"
20:21:18 Error in expression <ge", _prestige];
_session set ["Level", _level];
_session set ["XP", _xp];
_sess>
20:21:18   Error position: <_level];
_session set ["XP", _xp];
_sess>
20:21:18   Error Undefined variable in expression: _level
20:21:18 File life_server\Functions\Player\fn_registerSession.sqf..., line 25`

Any help would be appreciated! Thanks!

**Comment by Scarso327** [comment]
Hello @plcaco 

I've looked into this and haven't reproduced your issue, if you're setting up a fresh server you no longer need to apply migrations when using the development branch. If you did so this might be what caused the issue so try recreating the database only using the `altislife.sql` file.

There is also a fix in the development branch that might be of use and it ensures the default values for settings are used to avoid client-side errors I did experience when testing this.

Hope you're able to resolve your issue otherwise paste your server and client RPT logs on a site like https://pastebin.com/ and I'll take a deeper look.

**Comment by plcaco** [comment]
Hey thanks for replying so fast! I think the issue might actually be the DB, I still get the black screen but I was able to respawn and the black screen went away. I can interact with all the shops. but the Y-menu doesn't work and neither does unlocking cars. This was on a fresh install after your latest commits. There's nothing on my client RPT but I pasted below the ExtDB3 logs and the server RPT. I'm also using [FASTER ](https://github.com/Foxlider/FASTER )if that makes a difference.

ExtDB3: https://pastebin.com/A9RGkNvr
Server RPT: https://pastebin.com/ibvP2PHM

**Comment by Scarso327** [comment]
The error in your EXTDB3 file is because the auto-increment value against your `community_goals` table is set below the id(s) within the table. The framework uses the `SHOW TABLE STATUS` command to get the next auto-increment value. Wiping the contents of this table and retrying might resolve the issue or just changing the auto-increment value against the table. 

I am not able to reproduce a lot of the server RPT errors, in the mission file's `script_macros.hpp` file you can change the `IS_DEBUG_MODE` value to `true` which will enable further RPT output.

FASTER won't make a difference here I don't think, what database version are you using?

**Comment by plcaco** [comment]
I tried both wiping the contents of the table and changing the auto-increment but the same error occurs, it inserts one and then hits that error, I was able to get it to insert two rows by adding an `ON DUPLICATE KEY` statement to the query but that only inserted 2 rows before it hit the same error. I'm running MariaDB 11.4.

I'll keep doing some troubleshooting these days to see what's going on, seems like something's wrong on my end rather than something up with the Client/Server files. I'll update here if I'm able to solve it, also here is the server RPT logs with the debug mode in case something stands out to you, ExtDB3 still shows the same insert errors as above, thanks for the help so far!

https://pastebin.com/RvHBfELA

**Comment by plcaco** [comment]
I was able to fix the issue, not sure exactly what it was that did it but these were the only things I changed:

- FASTER was using **arma3server_x64.exe** to run the server, I just changed it to **arma3server.exe**, not sure what the difference is.

- In HeidiSQL the mariadb.sys user was missing some access to a table called **mysql.global_priv**, not entirely sure what that is either.

After doing both of these I received no black screen and prompted to select a spawn immediately, community goals also work as expected. Thanks for helping me look into it @Scarso327!
